common: temporarily do not verify SSL certificates in VzLinux (WA)
Apply the workaround (WA): temporarily do not verify SSL certificates
in VzLinux, because they have expired and the Docker image fails
to rebuild:

Step 3/28 : RUN dnf update -y
Errors during downloading metadata for repository 'virtuozzolinux-base':
  - Curl error (60): Peer certificate cannot be authenticated with \
                     given CA certificates for
    https://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-8-os
    [SSL certificate problem: certificate has expired]

Error: Failed to download metadata for repo 'virtuozzolinux-base': \
  Cannot prepare internal mirrorlist: \
  Curl error (60): Peer certificate cannot be authenticated with \
                   given CA certificates for \
  https://repo.virtuozzo.com/vzlinux/mirrorlist/mirrors-8-os \
  [SSL certificate problem: certificate has expired]

The command '/bin/sh -c dnf update -y' returned a non-zero code: 1