common: disable testing performance tools on OpenSUSE Tumbleweed
Temporarily disable testing performance tools on OpenSUSE Tumbleweed
due to the following issue:

Traceback (most recent call last):
  File "/home/user/.local/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
  File "/home/user/.local/lib/python3.10/site-packages/coverage/\
        /__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/user/.local/lib/python3.10/site-packages/coverage/\
        /control.py", line 23, in <module>
    from coverage.data import CoverageData, combine_parallel_data
  File "/home/user/.local/lib/python3.10/site-packages/coverage/\
        /data.py", line 18, in <module>
    from coverage.sqldata import CoverageData
  File "/home/user/.local/lib/python3.10/site-packages/coverage/\
        /sqldata.py", line 15, in <module>
    import sqlite3
  File "/usr/lib64/python3.10/_import_failed/sqlite3.py", line 16,\
        in <module>
    raise ImportError(f"""Module '{failed_name}' is not installed.
ImportError: Module 'sqlite3' is not installed.