examples: link 10-send-with-imm example with librt for glibc<2.17
clock_gettime() requires linking with -lrt
for glibc versions before 2.17.
It fixes the following error:

/usr/lib64/librpma.so: undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
/make[2]: *** [server] Error 1