tools: fix capturing stdout and stderr in subprocess.run()
'capture_output' and 'text' were introduced in pyton-3.7.
There is an error in case of python-3.6:

  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  TypeError: __init__() got an unexpected keyword argument \
  'capture_output'

and:

  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  TypeError: __init__() got an unexpected keyword argument 'text'