rpma: define advice and flags internally for rpma_mr_advise()
This change is to fix a compiler error due to undefined advice or flags.
For example:
error: ‘IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE’ undeclared
error: ‘IBV_ADVISE_MR_FLAG_FLUSH’ undeclared

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>