examples: fix error: variable 'is_pmem' set but not used
Fix the compilation error:

examples/09-flush-to-persistent-GPSPM/client.c:99:6: \
 error: variable 'is_pmem' set but not used \
 [-Werror=unused-but-set-variable]