common: install PMDK from sources instead of AUR on Arch Linux
It fixes the following error during compilation of PMDK:

../../src/../src/libpmem2/region_namespace_ndctl.c:9:10: \
  fatal error: ndctl/libdaxctl.h: No such file or directory
    9 | #include <ndctl/libdaxctl.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.