test: fix the "ibv_query_device_ex_mock undeclared" compiler error
When ON_DEMAND_PAGING_SUPPORTED is not defined and
NATIVE_ATOMIC_WRITE_SUPPORTED is defined, the following compiler error
will be triggered:
----------------------------------------------------------------------
...
error: 'ibv_query_device_ex_mock' undeclared (first use in this
	function); did you mean 'ibv_query_device_ex'?
...
----------------------------------------------------------------------

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>