common: remove the 'hub' package from Fedora rawhide docker file
Remove the 'hub' package from Fedora rawhide docker file,
because it is no longer available in this version:

No match for argument: hub
Error: Unable to find a match: hub